### PR TITLE
adding color to html body

### PR DESCRIPTION
**Pull request by Yewande-Adewale**

### CODE REVIEW

**Review by onyenze — APPROVED** [review]

**Review by Kennedy2042 — APPROVED** [review]
Yew and e you can do better than this

**Review by Grace-ekele — APPROVED** [review]

**Review by Yewande-Adewale — COMMENTED** [review]
sharp guy

**Review by Yewande-Adewale — COMMENTED** [review]
nice

**Review by Yewande-Adewale — COMMENTED** [review]
ok

**Review by Peterjoseph489 — COMMENTED** [review]
awesome

**Pull request merged**
